// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuBcAL774q6X-6yxKTEXezerz0lGYROH8',
    appId: '1:113124017004:web:b9404fd4ced0cabc09a949',
    messagingSenderId: '113124017004',
    projectId: 'chat-app-19238',
    authDomain: 'chat-app-19238.firebaseapp.com',
    storageBucket: 'chat-app-19238.appspot.com',
    measurementId: 'G-YP6ZKP2HQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDZ-y69ZmrsmXfiUH4dVt40Rba0Mq65CM',
    appId: '1:113124017004:android:f00797b82e8c737609a949',
    messagingSenderId: '113124017004',
    projectId: 'chat-app-19238',
    storageBucket: 'chat-app-19238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIX3WyZrtqeALQJVKu-xE5uYp7jl7x_Ck',
    appId: '1:113124017004:ios:f77b8b209de7cb5109a949',
    messagingSenderId: '113124017004',
    projectId: 'chat-app-19238',
    storageBucket: 'chat-app-19238.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
